name: lando-kt
recipe: drupal8
config:
  php: '7.4'
  via: nginx:1.18
  composer_version: "1.10.22"
  webroot: web
  database: mariadb
services:
  appserver:
    build_as_root:
      - "cd $LANDO_MOUNT && cp dev/settings.local.php web/sites/default"
      - "cd $LANDO_MOUNT && cp dev/development.services.yml web/sites"
